### ISSUE TITLE
Provide iCal endpoint

### ISSUE THREAD

**Issue by dragfyre** [edwardspec/mediawiki-extension-JsCalendar#1]
A cool feature that some of us have been discussing is to provide an endpoint that outputs the calendar in iCal format, which could then be used to subscribe to the calendar in whatever program you like to use.

**Comment by edwardspec** [comment]
This is a bit outside the scope of this extension,
but it is technically possible to add this feature into it (e.g. a possible approach is to call `MediaWiki\JsCalendar\EventCalendar::findEvents()` from a separate `SpecialPage` such as `Special:JsCalendarExport/PageNameThatHasCalendarTag`, and have this special page print its output as iCal).

I'm not really interested in implementing this myself, but feel free to submit a patch.

**Comment by samwilson** [comment]
Relatedly: the Cargo extension now has icalendar export functionality. (Just in case anyone finds this while evaluating different extensions with calendars.)

**Comment by edwardspec** [comment]
Closing, as nobody was interested in implementing this, and it's not a cosmetic feature to add it quickly.
