### ISSUE TITLE
Allow localisation of the extension interface messages

### ISSUE THREAD

**Issue by RhinosF1** [edwardspec/mediawiki-extension-JsCalendar#2]
https://phabricator.miraheze.org/T6137#121129

**Comment by edwardspec** [comment]
This extension doesn't define "Event" namespace (in hardcoded English). It only mentions it as example in README.
For a non-English wiki you can just use
```
    <EventCalendar>
    namespace = Name_of_localized_namespace
    </EventCalendar>
```

**Comment by RhinosF1** [comment]
Are they any other interface messages used?

**Comment by edwardspec** [comment]
The calendar is being rendered by third-party JavaScript library FullCalendar, which is fully localized.
In https://github.com/edwardspec/mediawiki-extension-JsCalendar/commit/6188b9241c1c062ea6531d96810b0cc1cd25bfc4, I instructed it to use the current user's language (or content language for anonymous users) to display things like "Monday", etc. So all labels should now be fully translated on non-English wikis.

**Comment by RhinosF1** [comment]
I'll take this back to the user.
