### ISSUE TITLE
aspectratio does not work out of the box

### ISSUE THREAD

**Issue by johannesnoordanus** [edwardspec/mediawiki-extension-JsCalendar#3]
Aspectratio set from a MediaWiki page (within `<EventCalendar>` .. `</EventCalendar>`) does not change the aspect ratio of the calendar within the page.
This is because configuration file _ext.yasec.core.js_ contains setting _contentHeight: 'auto'_ which disables (overrides) the aspect ratio setting. It is also important to set _max-with_ in _ext.yasec.css_ to a much larger size (1600px) on a desktop to be able to view the  aspectratio setting accurately.

**Comment by edwardspec** [comment]
`contentHeight: 'auto' ` was added in https://github.com/edwardspec/mediawiki-extension-JsCalendar/commit/a742e95596bf44a87b4b5b1c1b096d20370afd2c to remove the unwanted scrollbar. Do you have a solution that fixes aspectratio, but doesn't cause scrollbar to reappear?

**Comment by johannesnoordanus** [comment]
> `contentHeight: 'auto' ` was added in [a742e95](https://github.com/edwardspec/mediawiki-extension-JsCalendar/commit/a742e95596bf44a87b4b5b1c1b096d20370afd2c) to remove the unwanted scrollbar. Do you have a solution that fixes aspectratio, but doesn't cause scrollbar to reappear?

No, the scrollbar reappears. 
README.md doesn't mention that the 'auto height' setting is set and that it disables the aspectratio setting. Maybe add the auto setting as $wgAutoCalendarHeight to `LocalSettings.php` and indicate that this disables aspectration (within README.md)?

**Comment by edwardspec** [comment]
Fixed in 1765c0d4549e56fe95a8b59338c229955a706c81.
