### ISSUE TITLE
Bug: multi-day events are not displayed correctly - last day is missing

### ISSUE THREAD

**Issue by mtettke123** [edwardspec/mediawiki-extension-JsCalendar#8]
an event like
`Event:2023-11-14:2023-11-15 title`
is only displayed on day 1; an event like
`Event:2023-11-14:2023-11-16 title`
wouls be displayed on day 1 and 2 - last day is missing.

Calendar definition:
```
<EventCalendar>
namespace = Event
titleRegex = ^([0-9]{4,4}-[0-9][0-9]-[0-9][0-9]):?([0-9]{4,4}-[0-9][0-9]-[0-9][0-9])?_.*
dateFormat = Y-m-d
</EventCalendar>
```

**Comment by edwardspec** [comment]
Intended. That's how FullCalendar library treats end date.

From [https://fullcalendar.io/docs/event-object](https://fullcalendar.io/docs/event-object):

> This value is exclusive. For example, an event with the end of 2018-09-03 will appear to span through 2018-09-02 but end before the start of 2018-09-03

**Comment by mtettke123** [comment]
Wow, that's unusual. So if I have an event for two days I've to create a three day event? Maybe there could be an config setting for the behaviour?

**Comment by edwardspec** [comment]
Fixed, end day is no longer excluded by default.

Previous behavior can be restored by adding `excludeLastDay=1` parameter inside `<eventcalendar>` tag.
