### ISSUE TITLE
Calendar doesn't work with Extension:Lingo

### ISSUE THREAD

**Issue by mtettke123** [edwardspec/mediawiki-extension-JsCalendar#9]
I use the following call to include the calendar:
```
<EventCalendar>
namespace = Event
titleRegex = ^([0-9]{4,4}-[0-9][0-9]-[0-9][0-9]):?([0-9]{4,4}-[0-9][0-9]-[0-9][0-9])?_.*
dateFormat = Y-m-d
categorycolor.Marketingevents = #11aa11
</EventCalendar>

```
This worked well - but after adding another Event ("Event:2024-01-25_Meeting") the calender does not show up any more at all. Is there any way to debug why?

**Comment by edwardspec** [comment]
Any errors/warnings in the error log of php/webserver?
Any JavaScript errors in the browser console?

**Comment by mtettke123** [comment]
Yes, indeed. Tracked it down: We use the "lingo" extension. When there is a term that gets annotated by lingo, something like this happens:
![grafik](https://github.com/edwardspec/mediawiki-extension-JsCalendar/assets/82048170/7d514d12-22a9-4a30-82f1-64daccb77e08)
The code with the error is:

`...,{"title":"<span class="mw-lingo-term" data-lingo-term-id="8a6b178d3af0a5a9b2744ca31921d5e2">ZS</span>-Teammeeting","start":"2024-01-25","end":"2024-01-26","url":"/index.php/Event:2024-01-25_<span class="mw-lingo-term" data-lingo-term-id="8a6b178d3af0a5a9b2744ca31921d5e2">ZS</span>-Teammeeting"},...`

So what ever lingo includes there, is not escaped.

I was able to help myself with excluding the event-Namespace from lingo.

Thank you for the hint!

**Comment by mtettke123** [comment]
Problem seems to be worse that this: As long as lingo is enabled in NS_MAIN and there is a calender event that includes an abbreviaton in the title, the calendar does not work.

**Comment by edwardspec** [comment]
> So what ever lingo includes there, is not escaped.

It absolutely is escaped. The title can have any tags/quotes.
I overwrote the title of event with above-mentioned `span` tag, and it was escaped properly.

How does this script itself look? It is inline in the HTML of the page that has the calendar.

**Comment by mtettke123** [comment]
Can I send you the HTML of this page somehow via mail?

**Comment by edwardspec** [comment]
Yes, please send it to `edwardspec@gmail.com`.

**Comment by mtettke123** [comment]
> Yes, please send it to `edwardspec@gmail.com`.

ok, Mail is sent - hopefully not to SPAM.

**Comment by edwardspec** [comment]
Received.
Turns out, Extension:Lingo inserts this unescaped code (by doing regex replacements on the entire page, but not knowing that there is a script inside the page).

Please try the following: surround the `<eventcalendar></eventcalendar>` tag in `<div class="noglossary">` and `</div>`. It's what Extension:Lingo uses to prevent itself from breaking output of Extension:SimpleMathJax.

**Comment by mtettke123** [comment]
can confirm thats the solution. Thank you!
